//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaServicesManager.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Program
    {
        public Program()
        {
            this.ProgramDetails = new HashSet<ProgramDetail>();
        }
    
        public int ProgramId { get; set; }
        public string Type { get; set; }
        public System.DateTime TimeStart { get; set; }
        public string Description { get; set; }
        public System.DateTime EndTime { get; set; }
    
        public virtual ICollection<ProgramDetail> ProgramDetails { get; set; }
    }
}
