//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaServicesManager.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramDetail
    {
        public int ProgramDetailId { get; set; }
        public int ProgramProgramId { get; set; }
        public int ResourceResourceId { get; set; }
        public int PersonPersonId { get; set; }
    
        public virtual Program Program { get; set; }
        public virtual Resource Resource { get; set; }
        public virtual Person Person { get; set; }
    }
}
